name: dispatch-reciever
on:
  repository_dispatch:
    types:
      - image-published
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo "Deploying ${{  github.event.client_payload.image  }} image, \
          tag: ${{  github.event.client_payload.tag  }}, \
          on ${{  github.event.client_payload.environment  }} environment"
